version: 2

updates:
  - package-ecosystem: "github-actions"
    directories: [".github/workflows", ".github/actions/**"]
    schedule:
      interval: "daily"
    assignees: ["esuldin"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["esuldin"]
