version: 2

updates:
  - package-ecosystem: "github-actions"
    directories: [".github/workflows", ".github/actions/**"]
    schedule:
      interval: "daily"
    assignees: ["esuldin"]
    groups:
      codeql-action:
        patterns:
          - github/codeql-action/init
          - github/codeql-action/analyze
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["esuldin"]
