name: Install requirements
description: Install requirements for specific Python version.

author: Egor Suldin

runs:
  using: composite
  steps:
    - name: Get Python info
      id: python-info
      uses: ./.github/actions/get-python-info
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    - name: Install dependencies for Python 3.8
      if: steps.python-info.outputs.version == '3.8'
      run: |
        python -m pip install -r requirements-3.8.locked
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    # A workaround for lxml 6.0.1+ package
    - name: Install dependencies for PyPy3.9
      if: runner.os == 'Linux' && startsWith(steps.python-info.outputs.version, 'pypy')
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt1-dev
      shell: sh
    - name: Install dependencies for Python 3.9 and PyPy 3.9
      if: contains(fromJson('["3.9", "pypy3.9"]'), steps.python-info.outputs.version)
      run: |
        python -m pip install -r requirements-3.9.locked
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    - name: Install dependencies for Python 3.10+
      if: '!contains(fromJson(''["3.8", "3.9", "pypy3.9"]''), steps.python-info.outputs.version)'
      run: |
        python -m pip install -r requirements.txt
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
