name: Install requirements
description: Install requirements for specific Python version.

author: Egor Suldin
branding:
  icon: folder-plus
  color: yellow

inputs:
  python-version:
    description: Exact version of Python or PyPy to install the requirements for.
runs:
  using: composite
  steps:
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    - name: Install dependencies for Python 3.8
      if: inputs.python-version == '3.8'
      run: |
        python -m pip install -r requirements-3.8.locked
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    # A workaround for lxml 6.0.1+ package
    - name: Install dependencies for PyPy3.9
      if: runner.os == 'Linux' && matrix.python-version == 'pypy3.9'
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-dev libxslt1-dev
      shell: sh
    - name: Install dependencies for Python 3.9 and PyPy 3.9
      if: contains(fromJson('["3.9", "pypy3.9"]'), inputs.python-version)
      run: |
        python -m pip install -r requirements-3.9.locked
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
    - name: Install dependencies for Python 3.10+
      if: '!contains(fromJson(''["3.8", "3.9", "pypy3.9"]''), inputs.python-version)'
      run: |
        python -m pip install -r requirements.txt
      shell: ${{runner.os == 'Windows' && 'cmd' || 'sh'}}
