name: Checkout
description: Checkout a source code.

author: Egor Suldin
branding:
  icon: download
  color: green

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: recursive
