name: Run Bandit Scan
description: Analyzes the Python code with Bandit.

author: Egor Suldin

runs:
  using: composite
  steps:
    - name: Scan with Bandit (POSIX)
      if: runner.os != 'Windows'
      run: |
        bandit --ini .bandit -f sarif -o results.sarif -r || true
      shell: sh
    - name: Scan with Bandit (Windows)
      if: runner.os == 'Windows'
      run: |
        bandit --ini .bandit -f sarif -o results.sarif -r & ver>nul
      shell: cmd
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 #  v4.37.8
      with:
        sarif_file: results.sarif
