name: Build Python Package
description: Build Python Package for CPython 3.8+ and PyPy 3.9+.

runs:
  using: composite
  steps:
    - name: Build wheels
      uses: pypa/cibuildwheel@298ed2fb2c105540f5ed055e8a6ad78d82dd3a7e # v3.3.1
      env:
        CIBW_BUILD: "*-win32 *-win_amd64 *-manylinux_i686 *-manylinux_x86_64 *-musllinux_i686 *-musllinux_x86_64"
        CIBW_ENABLE: pypy
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux2014
        CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_2
        CIBW_MUSLLINUX_I686_IMAGE: musllinux_1_2
