name: Setup Python
description: Set up a specific version of Python.

author: Egor Suldin

inputs:
  python-version:
    description: Version range or exact version of Python or PyPy to use.

runs:
  using: composite
  steps:
    - name: Set up Python ${{inputs.python-version}}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        allow-prereleases: true
        python-version: ${{inputs.python-version}}
