name: Install pyitt module
description: Build and install pyitt module.

author: Egor Suldin
branding:
  icon: code
  color: yellow

inputs:
  pyitt-native-build-with-code-coverage:
    description: The value for PYITT_NATIVE_BUILD_WITH_CODE_COVERAGE environment variable.
    default: 'false'
runs:
  using: composite
  steps:
    - name: Build and install pyitt module
      env:
        PYITT_NATIVE_BUILD_WITH_CODE_COVERAGE: ${{inputs.pyitt-native-build-with-code-coverage}}
      run: |
        python -m pip install .
