name: Install C/C++ compilers
description: Install standard C/C++ compilers.

author: Egor Suldin

runs:
  using: composite
  steps:
    - name: Install MSVC
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
    - name: Install GCC compilers
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++
      shell: sh
