name: CI on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    uses: ./.github/workflows/codeql.yml
    permissions:
      security-events: write
  ci:
    uses: ./.github/workflows/ci.yml
  dependabot-auto-approve:
    uses: ./.github/workflows/dependabot-auto-approve.yml
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [ci]
    permissions:
      actions: write
      contents: write
      pull-requests: write
