name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  dependabot-auto-approve:
    uses: ./.github/workflows/dependabot-auto-approve.yml
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [ci]
    permissions:
      contents: write
      pull-requests: write
