name: CI on Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    uses: ./.github/workflows/codeql.yml
    permissions:
      security-events: write
  ci:
    uses: ./.github/workflows/ci.yml
