name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    name: Build & test on ${{matrix.os}}
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        # If the list of python versions is changed, please make sure that
        # `after_n_builds` flag in codecov.yml is updated accordingly
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', 'pypy3.9', 'pypy3.10', 'pypy3.11']
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Run CI Checks
        uses: ./.github/actions/run-ci-pipeline
        with:
          python-version: ${{matrix.os == 'windows-latest' && matrix.python-version == '3.14'
                             && '3.13.0 - 3.13.3 || 3.13.5 - 3.13'
                             || matrix.python-version}}

  build-wheels:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Build wheels
        uses: ./.github/actions/python-packages

  run-codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml
    permissions:
      contents: read
      security-events: write

  dependabot-auto-approve:
    uses: ./.github/workflows/dependabot-auto-approve.yml
    if: github.event.pull_request && github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [build-and-test, build-wheels, run-codeql]
    permissions:
      actions: write
      contents: write
      pull-requests: write
